language: php

php:
    - 7.2

before_script:
  - composer install --no-interaction --optimize-autoloader

script:
  - ./bin/phpunit
  - ./bin/console lint:twig ./templates
  - ./vendor/bin/phpstan analyse -c ./phpstan.neon --level max src
